const addition =require("./add")
const subtraction =require("./subtract")
const multiplication =require("./multiply")
const division =require("./divide")
console.log(addition(10,12))
 console.log(subtraction(20,6))
 console.log(multiplication(40,2))
 console.log(division(10,2))